artifact_uri: file:///home/mle-user/mle_projects/sprint2_ml_ops/mlflow_experiments_store/mlflow_experiments_store/0/5c503d8828d446e9a1146faa8b58184b/artifacts
end_time: 1735033983223
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5c503d8828d446e9a1146faa8b58184b
run_name: Default
run_uuid: 5c503d8828d446e9a1146faa8b58184b
source_name: ''
source_type: 4
source_version: ''
start_time: 1735033983208
status: 3
tags: []
user_id: mle-user
