artifact_uri: file:///home/mle-user/mle_projects/sprint2_ml_ops/mlflow_experiments_store/mlflow_experiments_store/0/150dc216d6624438a5642e2c49c33701/artifacts
end_time: 1735034130381
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 150dc216d6624438a5642e2c49c33701
run_name: Default
run_uuid: 150dc216d6624438a5642e2c49c33701
source_name: ''
source_type: 4
source_version: ''
start_time: 1735034130366
status: 3
tags: []
user_id: mle-user
