artifact_location: file:///home/mle-user/mle_projects/sprint2_ml_ops/mlflow_experiments_store/mlflow_experiments_store/0
creation_time: 1735033983090
experiment_id: '0'
last_update_time: 1735033983090
lifecycle_stage: active
name: Default
